version: '3'
services:

  react:
    container_name: client
    build: client
    restart: on-failure
    ports: 
      - "3000:3000"
  app:
    container_name: faucet
    build: faucet
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - faucet-mysql 

  faucet-mysql:
    image: mysql
    container_name: faucet-mysql
    restart: always
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=faucet-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=transaction
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - database_mysql:/var/lib/mysql
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: nginx
    ports:
      - 80:80
    
volumes:
  database_mysql:


